### ISSUE TITLE
Default system language

### ISSUE THREAD

**Issue by ivanmood** [Leleat/extensions-in-system-menu#2]
After enabling the extension, some system components change the default system language (Ukrainian) to English (after shell restart). For example: context menu (right click) on the desktop. Ubuntu 20.04.

**Comment by Leleat** [comment]
Hi, are you sure that this is caused by this extension? For example remove  (**not** just disable) the extension and restart the shell. Does the text appear in your default system language again? 

If so, can you make a screenshot of the text, which is in english?

**Comment by Leleat** [comment]
So I've installed an Ubuntu 20.04 VM and I can't reproduce this (with the current master branch). Steps I did:

0. Change system language to ukranian.
1. Install this extensions.
2. reboot.

Nothing seemed out of the ordinary. I also tried to disable and re-enable this extension. I restarted the GNOME Shell and I don't see english anywhere.

![Screenshot from 2021-02-15 13-42-44](https://user-images.githubusercontent.com/53054301/107948650-0a122d00-6f8c-11eb-96cd-b695a12cc97d.png)

So I don't think this may be related to my extension (...also don't know how my extension could even cause this). Could it be that the english was always there and just hasn't been translated to ukranian yet?

**Comment by ivanmood** [comment]
Yes, I'm sure. Prior to that, I encountered this problem in the "Night Light Slider" extension. But with the update it was fixed.
![Bug](https://user-images.githubusercontent.com/79090500/107952058-ebb72c00-6fa1-11eb-8d44-93aa571411cc.png)

**Comment by ivanmood** [comment]
Taking advantage of the moment, it would be great to add the ability to change places Extensions and Tweaks.
![abl](https://user-images.githubusercontent.com/79090500/107954452-2373a300-6fa5-11eb-83d0-b2cd0a69672b.png)

**Comment by Leleat** [comment]
No idea why the german translations messes up your translations. I followed the guide from the extensions wiki... oh well, whatever, I just removed the translations completely. So that should do it.

> Taking advantage of the moment, it would be great to add the ability to change places Extensions and Tweaks.

Added now.
