### ISSUE TITLE
Swap Extensions and Tweaks

### ISSUE THREAD

**Issue by ivanmood** [Leleat/extensions-in-system-menu#3]
I confirm that the language problem has been resolved.
As for the ability to swap Extensions and Tweaks, thank you for adding such a feature, but if you set the position for Tweaks: '2', and for Extensions: '3', then after restarting the shell, the position of the Extensions is lost.
![bg](https://user-images.githubusercontent.com/79090500/107964155-ab5faa00-6fb1-11eb-850f-1c7aaf237af6.png)

**Comment by Leleat** [comment]
This isn'ta bug but just the way the extensions work. 

The menu items get added in the order of `Extensions` and then `Tweaks`. And the position will vary depending on how many items are in the menu already.

So what is happening in your case:

1. At first there is only `Settings`, `Lock` and the `Power` menu. Then `Extensions` gets added to the 3rd position (i .e. after `Lock`).
2. Now there `Settings`, `Lock`, `Extensions` and the `Power` menu. Now `Tweaks` will be added after `Settings`.

**Comment by Leleat** [comment]
So if you want to have Settings>Tweaks>Extensions>Lock.. the positions need to be Extensions: 2 and Tweaks: 2.

**Comment by ivanmood** [comment]
Yes, I saw it, I forgot to report. But then the logic of consistency is somewhat lost in my understanding.

**Comment by ivanmood** [comment]
If the position '2' is set equally for both, then it is not known what will be displayed first. In the opinion of the average user, this looks strange. It will be more logical to display positions '2' and '3', '1' and '2', etc., while position  '2 ' and  '2 ' will look random.

**Comment by Leleat** [comment]
Fair enough. Now all items will get recreated when changing a setting. This should adress your issue.

**Comment by Leleat** [comment]
Although you can still set them to have the same number, which may result in weird edge cases

**Comment by ivanmood** [comment]
Oh, I am very grateful to you.
