### ISSUE TITLE
app.app_info.get_icon().names is undefined

### ISSUE THREAD

**Issue by ghost** [Leleat/extensions-in-system-menu#4]
Hi,

I'm using Gnome Shell 3.38.3, and can't install your extension.

I get an error: app.app_info.get_icon().names is undefined

I uninstalled it, restarted Gnome-Shell (alt+F2 -> r) then reinstalled it, same situation

Any piece of advice ?

**Comment by Leleat** [comment]
That is rather unexpected. Can you tell me your Distro, wether you have `GNOME Extensions`and/or `GNOME Tweaks` installed and maybe what icons you use?

**Comment by ghost** [comment]
I'm using Kali Linux 2021.1 with Gnome 3.38.3
I have both Gnome-Tweaks and Gnome-Extensions installed, but I use more Gnome-Extensions to manage (enable/disable/remove) my extensions
When I enable the extension from Gnome-Tweaks, nothing happened, it doesn't enable it
When I enable it from Gnome-Extensions, I get the :-( shape with the mentioned error

**Comment by Leleat** [comment]
> When I enable the extension from Gnome-Tweaks, nothing happened, it doesn't enable it

`Tweaks` is a bit outdated when it comes to extensions. In the latest/upcoming cycle (GNOME 40) they already removed the extensions part from `Tweaks`. The `Extensions-app` should be used from now on.

> When I enable it from Gnome-Extensions, I get the :-( shape with the mentioned error

I'll try to run Kali linux in a VM to pinpoint the problem. I'll report back once I've figured out how to fix it.

**Comment by Leleat** [comment]
So I've installed Kali Linux in a VM and I can't reproduce it with the default settings.

![Screenshot from 2021-03-06 13-02-19](https://user-images.githubusercontent.com/53054301/110206249-7d64db80-7e74-11eb-941d-9fe45652f1d6.png)

Do you use any custom settings which might influence the icons? For ex. did you change the icon "theme"?

**Comment by ghost** [comment]
Yeah I tired the same thing in my kali gnome live.
It works great, but not in my system.

Yeah I used custom theme, icons, cursor, and shell theme

**Comment by Leleat** [comment]
> Yeah I used custom theme, icons, cursor, and shell theme

Can you tell me the name of your icon theme?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/23521148/110206405-b6ee1480-7e7d-11eb-8451-b94e25a8151a.png)

**Comment by ghost** [comment]
I tried with default Adwaita, still not working

**Comment by Leleat** [comment]
Did you also restart the gnome shell after switching to Adwaita? If yes, the problem is too low-level for me and I don't know how to fix it, sorry...

One last "workaround" you can try is replace `app.app_info.get_icon().names[0]` in Line 79  with `appID.slice(0, appID.lastIndexOf("."))`. Restart gnome shell after changing the line.

**Comment by ghost** [comment]
Yeah I always do "Alt+F2, then r"

Although, the workaround works, and that's what I did:

I commented this line 79
`//const [name, icon] = [app.get_name(), app.app_info.get_icon().names[0]];`

I've copied it and modified
`const [name, icon] = [app.get_name(), appID.slice(0, appID.lastIndexOf("."))];`

Maybe you can commit it and push a new minor version ?

**Comment by Leleat** [comment]
> Maybe you can commit it?

Done. Will also upload it to EGO. Give it a week or so until it is reviewed.

**Comment by Leleat** [comment]
Actually, I just noticed that there is a method to directly get the icon for an app. I've pushed a new commit. Can you test, if that commit still works for you?

**Comment by ghost** [comment]
Yep, the new commit is ok, it works.

I definitely see my Extension App customized logo in the system menu, instead of the original one.

Thanks ;-)

**Comment by ghost** [comment]
Now I understand what the bug was.

After your commit, my customized logo appeared 
![image](https://user-images.githubusercontent.com/23521148/110212216-98e2dd00-7e9a-11eb-9d39-2d34ba259c7c.png)

After reinstalling gnome-extensions app, the default logo is back (theme applied)
![image](https://user-images.githubusercontent.com/23521148/110212242-b748d880-7e9a-11eb-8886-8b2ced18603b.png)

It's my customized icon who crashed your extension, hmm now I see
